<a href="https://colab.research.google.com/github/DipeshPun/Image-Processing/blob/main/IPLab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([1,2,3])
a.ndim
a

array([1, 2, 3])

In [ ]:
x=a.reshape(1,3)
x

array([[1, 2, 3]])

In [ ]:
import numpy as np
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [ ]:
a[1,5]

13

In [ ]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
a[:,0]

array([1, 8])

In [ ]:
a[0,1:-1:2]

array([2, 4, 6])

In [ ]:
a[:,2]

array([ 3, 10])

In [ ]:
a[1,5]=20
a[:,2]=[1,2]
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [ ]:
a.shape

(2, 7)

In [ ]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
c.shape

(1, 3, 3)

In [ ]:
c.ndim

3

In [ ]:
b = np.array([[[1,2,],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
b.ndim

3

In [ ]:
b.shape

(2, 2, 2)

In [ ]:
b[0,1,1]

4

In [ ]:
b[1,1,1]

8

In [ ]:
b[1,1,0]

7

In [ ]:
b[0,1,0]

3

In [ ]:
b[1,0,1]

6

In [ ]:
tnsor = np.array([[[[1,2,3],[3,4,7]],[[5,6,9],[7,8,4]]],
                [[[1,2,3],[3,4,7]],[[5,16,9],[7,8,4]]]])
print(tnsor.ndim)

4


In [ ]:
tnsor.shape

(2, 2, 2, 3)

In [ ]:
tnsor

array([[[[ 1,  2,  3],
         [ 3,  4,  7]],

        [[ 5,  6,  9],
         [ 7,  8,  4]]],


       [[[ 1,  2,  3],
         [ 3,  4,  7]],

        [[ 5, 16,  9],
         [ 7,  8,  4]]]])

In [ ]:
tnsor[0,0,0,2]

3

In [ ]:
y=np.array([[1,2,3],[4,5,6]])
y

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
d=y[0,1]+y[1,1]
d

7

In [ ]:
d=np.sum(y,axis=0)
d

array([5, 7, 9])

In [ ]:
d=np.sum(y,axis=1)
d

array([ 6, 15])

In [ ]:
d=np.concatenate((y,y),axis=0)
d

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
d=np.concatenate((y,y),axis=1)
d

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
#Element wise multiplication
import numpy as np
a = np.array([15,10,20])
b = np.array([1,2,5])
c = a*b
print(c)

[ 15  20 100]


In [ ]:
#Dot Product
a = np.array([15,10,20])
b = np.array([1,2,5])
c = a.dot(b)
print(c)

135


In [ ]:
#But Matrix multiplication/dot product is Not Commutative --> AB != BC
b=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

a=np.array([[2,4,5],
           [3,6,7],
           [1,8,9]])
x=np.array([[4,5,6],
           [8,9,1],
           [6,2,4]])

c=a*b
print(c)
d=a.dot(b)
print(d)

[[ 2  8 15]
 [12 30 42]
 [ 7 64 81]]
[[ 53  64  75]
 [ 76  92 108]
 [ 96 114 132]]


In [ ]:
#Matrix multiplication is distributive --> A(B+C) = AB + AC and Associative --> A(BC) = (AB)C
c=x+a
print(c)
d=b*c
print(d)
print(a*b)
print(b*x)
print(a*b+b*x)

[[ 6  9 11]
 [11 15  8]
 [ 7 10 13]]
[[  6  18  33]
 [ 44  75  48]
 [ 49  80 117]]
[[ 2  8 15]
 [12 30 42]
 [ 7 64 81]]
[[ 4 10 18]
 [32 45  6]
 [42 16 36]]
[[  6  18  33]
 [ 44  75  48]
 [ 49  80 117]]


In [ ]:
#Dot product of two vectors commutative aTb=bTa
aT=a.T
bT=b.T
print(aT*b)
print(bT*a)

[[ 2  6  3]
 [16 30 48]
 [35 56 81]]
[[ 2 16 35]
 [ 6 30 56]
 [ 3 48 81]]


In [ ]:
# Transpose (ab)T=aTbT
y=a*b
print(y.T)
print(aT*bT)

[[ 2 12  7]
 [ 8 30 64]
 [15 42 81]]
[[ 2 12  7]
 [ 8 30 64]
 [15 42 81]]


In [ ]:
#Below code decomposes a matrix into its eigen vectors and values
import numpy as np
A = np.array([[2,3],[3,1]])
print("The matrix A is")
print(A)

egn_val, en_vctr = np.linalg.eig([[2,3],[3,1]])
print("The eigen values of the matrix A are",egn_val)
print("The eigen vectors of the matrix A are")
print(en_vctr )

The matrix A is
[[2 3]
 [3 1]]
The eigen values of the matrix A are [ 4.54138127 -1.54138127]
The eigen vectors of the matrix A are
[[ 0.76301998 -0.6463749 ]
 [ 0.6463749   0.76301998]]


In [ ]:
#Confirm eigen decompostion equation
import numpy as np
from numpy.linalg import eig
A = np.array([[2,3],[3,1]])
print(A)
egn_val, en_vctr  = eig(A)
Left_Av0 = A.dot(en_vctr [:,0])  ## First eigen vector  vectors[:,0]
print(Left_Av0)


Right_lamdv0 = en_vctr [:,0].dot(egn_val[0])
print("The values of AV = Left_Av0 is ", Left_Av0 ,"and values of lambda * V = Right_lamdv0 =  ",Right_lamdv0,"are same" )

[[2 3]
 [3 1]]
[3.46516465 2.93543484]
The values of AV = Left_Av0 is  [3.46516465 2.93543484] and values of lambda * V = Right_lamdv0 =   [3.46516465 2.93543484] are same


In [ ]:
#Original Matrix Reconstruction using eigen values and vectors
from numpy import diag
from numpy.linalg import inv
from numpy import array
from numpy.linalg import eig
# define matrix
A = np.array([[2,3],[3,1]])
# factorize the matrix into eigen vectors and values
egn_val, en_vctr  = eig(A)
# create matrix from eigenvectors
V = en_vctr
# create inverse of eigenvectors matrix
V_I = inv(en_vctr)
# create diagonal matrix from eigenvalues
Lambda = diag(egn_val)
# reconstruct the original matrix from eigenvalues and eigenvectors
Reconstrc_Mtrx = V.dot(Lambda).dot(V_I)
print("The original matrix A is")
print(A)
print("The reconstructed matrix is")
print(Reconstrc_Mtrx)

The original matrix A is
[[2 3]
 [3 1]]
The reconstructed matrix is
[[2. 3.]
 [3. 1.]]


In [ ]:
# mean of the column by specifying axis = 0 in the mean() function
# mean of the row elements of a matrix by specifying axis = 1 in the mean() function
import numpy as np
M = np.array([[8,1,3,6],[3,1,3,-2]])
rw_mn = np.mean(M,axis= 1)
print("The row wise mean of each subarray  is", rw_mn)
cl_mn = np.mean(M, axis = 0)
print("The column mean is ", cl_mn)

The row wise mean of each subarray  is [4.5  1.25]
The column mean is  [5.5 1.  3.  2. ]
